OLED_ENABLE = yes
OLED_DRIVER = ssd1306
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
HAPTIC_ENABLE = no
HAPTIC_DRIVER = drv2605l
DYNAMIC_MACRO_ENABLE = no
SWAP_HANDS_ENABLE = no

AUDIO_ENABLE = no
MUSIC_ENABLE = no

RGB_MATRIX_ENABLE = no

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_INSECURE = yes