# Build Options
#   change yes to no to disable
#
SWAP_HANDS_ENABLE = no

OLED_DRIVER = ssd1306

HAPTIC_DRIVER = drv2605l

RGB_MATRIX_SUPPORTED = yes

#SPACE SAVING
AUDIO_ENABLE = no
MUSIC_ENABLE = no
LTO_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no